# trading/signals/base.py
"""
NEXUS AI TRADING SYSTEM - Signal Base Module
Copyright © 2026 NEXUS QUANTUM LTD - All Rights Reserved
CEO: Dr X... - Majority Shareholder

This module provides the core signal definitions and base classes for
the NEXUS AI Trading System signal infrastructure. It defines the
fundamental signal types, data structures, and interfaces used
throughout the signal processing pipeline.

Key Features:
- Signal data models
- Signal type definitions
- Signal strength enumeration
- Signal validation
- Signal serialization
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple, Union
import uuid
import json

from shared.utilities.logger import get_logger
from shared.types.common import OrderSide, OrderType

logger = get_logger(__name__)


# ============================================================================
# ENUMS
# ============================================================================

class SignalType(str, Enum):
    """
    Types of trading signals.
    
    BUY: Signal to enter a long position
    SELL: Signal to enter a short position
    CLOSE: Signal to close an existing position
    NEUTRAL: No signal, wait
    HOLD: Maintain current position
    """
    BUY = "buy"
    SELL = "sell"
    CLOSE = "close"
    NEUTRAL = "neutral"
    HOLD = "hold"


class SignalStrength(str, Enum):
    """
    Strength of a trading signal.
    
    WEAK: Low conviction signal
    MEDIUM: Moderate conviction signal
    STRONG: High conviction signal
    VERY_STRONG: Maximum conviction signal
    """
    WEAK = "weak"
    MEDIUM = "medium"
    STRONG = "strong"
    VERY_STRONG = "very_strong"


class SignalSource(str, Enum):
    """
    Source of a trading signal.
    
    STRATEGY: Generated by a trading strategy
    INDICATOR: Generated by technical indicators
    PATTERN: Generated by pattern recognition
    AI: Generated by AI/ML models
    MANUAL: Manually entered by user
    EXTERNAL: Received from external source
    """
    STRATEGY = "strategy"
    INDICATOR = "indicator"
    PATTERN = "pattern"
    AI = "ai"
    MANUAL = "manual"
    EXTERNAL = "external"


# ============================================================================
# MODELS
# ============================================================================

@dataclass
class Signal:
    """
    Core trading signal data structure.
    
    Represents a trading decision generated by a strategy or indicator
    with associated metadata for execution and tracking.
    
    Attributes:
        symbol: Trading symbol (e.g., BTC/USD)
        signal_type: Type of signal (BUY/SELL/CLOSE/NEUTRAL/HOLD)
        strength: Signal strength indicator
        confidence: Confidence level (0.0 to 1.0)
        price: Price at signal generation
        position_size: Recommended position size (optional)
        stop_loss: Stop loss price (optional)
        take_profit: Take profit price (optional)
        timestamp: Signal generation time
        expiry: Signal expiry time (optional)
        signal_id: Unique signal identifier
        source: Signal source
        strategy_id: ID of generating strategy
        metadata: Additional signal metadata
        tags: Classification tags
        priority: Signal priority (1-10, higher = more urgent)
    """
    symbol: str
    signal_type: SignalType
    strength: SignalStrength = SignalStrength.MEDIUM
    confidence: float = 0.5
    price: float = 0.0
    position_size: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    timestamp: datetime = field(default_factory=datetime.utcnow)
    expiry: Optional[datetime] = None
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source: SignalSource = SignalSource.STRATEGY
    strategy_id: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    tags: List[str] = field(default_factory=list)
    priority: int = 5  # 1-10, default 5
    
    def __post_init__(self):
        """Validate signal on creation."""
        self._validate()
        # Set default expiry if not provided
        if self.expiry is None:
            self.expiry = self.timestamp + timedelta(minutes=5)
    
    def _validate(self) -> None:
        """Validate signal data."""
        if not self.symbol or not self.symbol.strip():
            raise ValueError("Symbol is required")
        
        if self.confidence < 0.0 or self.confidence > 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")
        
        if self.price < 0:
            raise ValueError("Price must be non-negative")
        
        if self.priority < 1 or self.priority > 10:
            raise ValueError("Priority must be between 1 and 10")
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary for serialization."""
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "strength": self.strength.value,
            "confidence": self.confidence,
            "price": self.price,
            "position_size": self.position_size,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "timestamp": self.timestamp.isoformat(),
            "expiry": self.expiry.isoformat() if self.expiry else None,
            "source": self.source.value,
            "strategy_id": self.strategy_id,
            "metadata": self.metadata,
            "tags": self.tags,
            "priority": self.priority,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Signal":
        """Create signal from dictionary."""
        return cls(
            symbol=data["symbol"],
            signal_type=SignalType(data["signal_type"]),
            strength=SignalStrength(data.get("strength", "medium")),
            confidence=data.get("confidence", 0.5),
            price=data.get("price", 0.0),
            position_size=data.get("position_size"),
            stop_loss=data.get("stop_loss"),
            take_profit=data.get("take_profit"),
            timestamp=datetime.fromisoformat(data["timestamp"]) if isinstance(data.get("timestamp"), str) else data.get("timestamp", datetime.utcnow()),
            expiry=datetime.fromisoformat(data["expiry"]) if data.get("expiry") else None,
            signal_id=data.get("signal_id", str(uuid.uuid4())),
            source=SignalSource(data.get("source", "strategy")),
            strategy_id=data.get("strategy_id", ""),
            metadata=data.get("metadata", {}),
            tags=data.get("tags", []),
            priority=data.get("priority", 5),
        )
    
    def to_json(self) -> str:
        """Convert signal to JSON string."""
        return json.dumps(self.to_dict(), default=str)
    
    @classmethod
    def from_json(cls, json_str: str) -> "Signal":
        """Create signal from JSON string."""
        return cls.from_dict(json.loads(json_str))
    
    def is_expired(self) -> bool:
        """Check if signal has expired."""
        if self.expiry is None:
            return False
        return datetime.utcnow() > self.expiry
    
    def is_buy(self) -> bool:
        """Check if signal is a BUY signal."""
        return self.signal_type == SignalType.BUY
    
    def is_sell(self) -> bool:
        """Check if signal is a SELL signal."""
        return self.signal_type == SignalType.SELL
    
    def is_close(self) -> bool:
        """Check if signal is a CLOSE signal."""
        return self.signal_type == SignalType.CLOSE
    
    def is_neutral(self) -> bool:
        """Check if signal is NEUTRAL."""
        return self.signal_type == SignalType.NEUTRAL
    
    def is_hold(self) -> bool:
        """Check if signal is HOLD."""
        return self.signal_type == SignalType.HOLD
    
    def is_actionable(self) -> bool:
        """Check if signal is actionable (BUY/SELL/CLOSE)."""
        return self.signal_type in [SignalType.BUY, SignalType.SELL, SignalType.CLOSE]
    
    def get_order_side(self) -> Optional[OrderSide]:
        """
        Get the corresponding order side.
        
        Returns:
            Optional[OrderSide]: Order side or None if not applicable
        """
        if self.signal_type == SignalType.BUY:
            return OrderSide.BUY
        elif self.signal_type == SignalType.SELL:
            return OrderSide.SELL
        elif self.signal_type == SignalType.CLOSE:
            # This is ambiguous without position context
            return None
        return None
    
    def get_strength_score(self) -> int:
        """
        Get numeric score for signal strength.
        
        Returns:
            int: Strength score (1-4)
        """
        scores = {
            SignalStrength.WEAK: 1,
            SignalStrength.MEDIUM: 2,
            SignalStrength.STRONG: 3,
            SignalStrength.VERY_STRONG: 4,
        }
        return scores.get(self.strength, 2)
    
    def __str__(self) -> str:
        return f"Signal({self.signal_id[:8]}, {self.symbol}, {self.signal_type.value}, conf={self.confidence:.2f})"
    
    def __repr__(self) -> str:
        return f"<Signal {self.signal_id[:8]} {self.symbol} {self.signal_type.value} {self.strength.value} {self.confidence:.2f}>"


# ============================================================================
# SIGNAL FACTORY
# ============================================================================

class SignalFactory:
    """
    Factory class for creating signals with convenience methods.
    """
    
    @staticmethod
    def create_buy(
        symbol: str,
        price: float,
        confidence: float = 0.6,
        strength: SignalStrength = SignalStrength.MEDIUM,
        position_size: Optional[float] = None,
        stop_loss: Optional[float] = None,
        take_profit: Optional[float] = None,
        strategy_id: str = "",
        source: SignalSource = SignalSource.STRATEGY,
        metadata: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
        priority: int = 5,
    ) -> Signal:
        """Create a BUY signal."""
        return Signal(
            symbol=symbol,
            signal_type=SignalType.BUY,
            strength=strength,
            confidence=confidence,
            price=price,
            position_size=position_size,
            stop_loss=stop_loss,
            take_profit=take_profit,
            source=source,
            strategy_id=strategy_id,
            metadata=metadata or {},
            tags=tags or [],
            priority=priority,
        )
    
    @staticmethod
    def create_sell(
        symbol: str,
        price: float,
        confidence: float = 0.6,
        strength: SignalStrength = SignalStrength.MEDIUM,
        position_size: Optional[float] = None,
        stop_loss: Optional[float] = None,
        take_profit: Optional[float] = None,
        strategy_id: str = "",
        source: SignalSource = SignalSource.STRATEGY,
        metadata: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
        priority: int = 5,
    ) -> Signal:
        """Create a SELL signal."""
        return Signal(
            symbol=symbol,
            signal_type=SignalType.SELL,
            strength=strength,
            confidence=confidence,
            price=price,
            position_size=position_size,
            stop_loss=stop_loss,
            take_profit=take_profit,
            source=source,
            strategy_id=strategy_id,
            metadata=metadata or {},
            tags=tags or [],
            priority=priority,
        )
    
    @staticmethod
    def create_close(
        symbol: str,
        price: float,
        confidence: float = 0.8,
        strategy_id: str = "",
        source: SignalSource = SignalSource.STRATEGY,
        metadata: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
        priority: int = 7,
    ) -> Signal:
        """Create a CLOSE signal."""
        return Signal(
            symbol=symbol,
            signal_type=SignalType.CLOSE,
            strength=SignalStrength.STRONG,
            confidence=confidence,
            price=price,
            source=source,
            strategy_id=strategy_id,
            metadata=metadata or {},
            tags=tags or [],
            priority=priority,
        )
    
    @staticmethod
    def create_neutral(
        symbol: str,
        price: float = 0.0,
        strategy_id: str = "",
        source: SignalSource = SignalSource.STRATEGY,
        metadata: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
    ) -> Signal:
        """Create a NEUTRAL signal."""
        return Signal(
            symbol=symbol,
            signal_type=SignalType.NEUTRAL,
            strength=SignalStrength.WEAK,
            confidence=0.5,
            price=price,
            source=source,
            strategy_id=strategy_id,
            metadata=metadata or {},
            tags=tags or [],
            priority=1,
        )
    
    @staticmethod
    def create_hold(
        symbol: str,
        price: float = 0.0,
        strategy_id: str = "",
        source: SignalSource = SignalSource.STRATEGY,
        metadata: Optional[Dict[str, Any]] = None,
        tags: Optional[List[str]] = None,
    ) -> Signal:
        """Create a HOLD signal."""
        return Signal(
            symbol=symbol,
            signal_type=SignalType.HOLD,
            strength=SignalStrength.WEAK,
            confidence=0.5,
            price=price,
            source=source,
            strategy_id=strategy_id,
            metadata=metadata or {},
            tags=tags or [],
            priority=2,
        )


# ============================================================================
# SIGNAL VALIDATOR
# ============================================================================

class SignalValidator:
    """
    Validator for signals.
    
    Provides methods to validate signal data and check signal quality.
    """
    
    @staticmethod
    def validate(signal: Signal) -> Tuple[bool, Optional[str]]:
        """
        Validate a signal.
        
        Args:
            signal: Signal to validate
            
        Returns:
            Tuple[bool, Optional[str]]: (is_valid, error_message)
        """
        try:
            signal._validate()
            return True, None
        except ValueError as e:
            return False, str(e)
    
    @staticmethod
    def is_quality_signal(signal: Signal, min_confidence: float = 0.5) -> bool:
        """
        Check if signal meets quality standards.
        
        Args:
            signal: Signal to check
            min_confidence: Minimum confidence threshold
            
        Returns:
            bool: True if signal meets quality standards
        """
        if not signal.is_actionable():
            return False
        
        if signal.confidence < min_confidence:
            return False
        
        if signal.strength == SignalStrength.WEAK:
            return False
        
        if signal.price <= 0:
            return False
        
        return True
    
    @staticmethod
    def get_quality_score(signal: Signal) -> float:
        """
        Calculate a quality score for the signal.
        
        Args:
            signal: Signal to score
            
        Returns:
            float: Quality score (0-1)
        """
        if not signal.is_actionable():
            return 0.0
        
        # Confidence contribution (0-0.4)
        confidence_score = signal.confidence * 0.4
        
        # Strength contribution (0-0.3)
        strength_scores = {
            SignalStrength.WEAK: 0.05,
            SignalStrength.MEDIUM: 0.15,
            SignalStrength.STRONG: 0.25,
            SignalStrength.VERY_STRONG: 0.30,
        }
        strength_score = strength_scores.get(signal.strength, 0.15)
        
        # Price reasonableness (0-0.1)
        if signal.price > 0:
            price_score = 0.1
        else:
            price_score = 0
        
        # Stop loss presence (0-0.1)
        stop_score = 0.1 if signal.stop_loss is not None else 0
        
        # Take profit presence (0-0.1)
        take_score = 0.1 if signal.take_profit is not None else 0
        
        return min(1.0, confidence_score + strength_score + price_score + stop_score + take_score)


# ============================================================================
# EXPORTS
# ============================================================================

__all__ = [
    # Enums
    "SignalType",
    "SignalStrength",
    "SignalSource",
    
    # Models
    "Signal",
    
    # Factory
    "SignalFactory",
    
    # Validator
    "SignalValidator",
]
