# trading/strategies/base.py
"""
NEXUS AI TRADING SYSTEM - Base Strategy Module
Copyright © 2026 NEXUS QUANTUM LTD - All Rights Reserved
CEO: Dr X... - Majority Shareholder

This module provides the abstract base class for all trading strategies
in the NEXUS AI Trading System. All strategy implementations must inherit
from this class and implement the required methods.

The base strategy class provides common functionality for:
- Signal generation
- Position management
- Risk management
- Performance tracking
- Strategy lifecycle management
- Configuration handling
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple, Union, Callable, Awaitable
import asyncio
import logging
import time
import uuid
from collections import deque

from shared.utilities.logger import get_logger
from shared.types.common import OrderSide, OrderType, TimeInForce
from shared.types.trading import Order, Position, Trade, MarketData, OrderBook


# ============================================================================
# ENUMS AND MODELS
# ============================================================================

class StrategyType(str, Enum):
    """Types of trading strategies"""
    TREND_FOLLOWING = "trend_following"
    MEAN_REVERSION = "mean_reversion"
    BREAKOUT = "breakout"
    ARBITRAGE = "arbitrage"
    SCALPING = "scalping"
    MOMENTUM = "momentum"
    GRID = "grid"
    AI_ENSEMBLE = "ai_ensemble"
    MACHINE_LEARNING = "machine_learning"
    DEEP_LEARNING = "deep_learning"
    REINFORCEMENT = "reinforcement"
    SENTIMENT = "sentiment"
    CUSTOM = "custom"


class StrategyState(str, Enum):
    """States of a strategy"""
    CREATED = "created"
    INITIALIZED = "initialized"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"
    TERMINATED = "terminated"


class SignalType(str, Enum):
    """Types of trading signals"""
    BUY = "buy"
    SELL = "sell"
    CLOSE = "close"
    NEUTRAL = "neutral"
    HOLD = "hold"


class SignalStrength(str, Enum):
    """Strength of a trading signal"""
    WEAK = "weak"
    MEDIUM = "medium"
    STRONG = "strong"
    VERY_STRONG = "very_strong"


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Attributes:
        symbol: Trading symbol
        signal_type: Type of signal (BUY/SELL/CLOSE/NEUTRAL/HOLD)
        strength: Signal strength
        confidence: Confidence level (0-1)
        price: Price at signal generation
        timestamp: Signal generation time
        metadata: Additional data
        position_size: Recommended position size
        stop_loss: Stop loss price
        take_profit: Take profit price
        expiry: Signal expiry time
    """
    symbol: str
    signal_type: SignalType
    strength: SignalStrength = SignalStrength.MEDIUM
    confidence: float = 0.5
    price: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)
    position_size: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    expiry: Optional[datetime] = None
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "strength": self.strength.value,
            "confidence": self.confidence,
            "price": self.price,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
            "position_size": self.position_size,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "expiry": self.expiry.isoformat() if self.expiry else None,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Signal":
        """Create signal from dictionary."""
        return cls(
            symbol=data["symbol"],
            signal_type=SignalType(data["signal_type"]),
            strength=SignalStrength(data.get("strength", "medium")),
            confidence=data.get("confidence", 0.5),
            price=data.get("price", 0.0),
            timestamp=datetime.fromisoformat(data["timestamp"]) if isinstance(data["timestamp"], str) else data.get("timestamp", datetime.utcnow()),
            metadata=data.get("metadata", {}),
            position_size=data.get("position_size"),
            stop_loss=data.get("stop_loss"),
            take_profit=data.get("take_profit"),
            expiry=datetime.fromisoformat(data["expiry"]) if data.get("expiry") else None,
            signal_id=data.get("signal_id", str(uuid.uuid4())),
        )


@dataclass
class StrategyConfig:
    """
    Configuration for a trading strategy.
    
    Attributes:
        name: Strategy name
        strategy_type: Type of strategy
        symbol: Trading symbol (can be None for multi-symbol)
        timeframe: Trading timeframe
        max_positions: Maximum number of concurrent positions
        position_size: Default position size
        max_position_size: Maximum position size
        min_position_size: Minimum position size
        risk_per_trade: Risk per trade (percentage of capital)
        stop_loss_pct: Default stop loss percentage
        take_profit_pct: Default take profit percentage
        trailing_stop_pct: Trailing stop percentage
        max_drawdown: Maximum allowed drawdown
        min_confidence: Minimum confidence for signal execution
        cooldown: Cooldown period after trade in seconds
        backtest_mode: Whether in backtest mode
        params: Additional strategy parameters
    """
    name: str = "BaseStrategy"
    strategy_type: StrategyType = StrategyType.CUSTOM
    symbol: Optional[str] = None
    timeframe: str = "1h"
    max_positions: int = 1
    position_size: float = 1000.0
    max_position_size: float = 100000.0
    min_position_size: float = 10.0
    risk_per_trade: float = 0.01  # 1%
    stop_loss_pct: float = 0.02  # 2%
    take_profit_pct: float = 0.04  # 4%
    trailing_stop_pct: float = 0.0
    max_drawdown: float = 0.10  # 10%
    min_confidence: float = 0.5
    cooldown: int = 0
    backtest_mode: bool = False
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategyMetrics:
    """
    Performance metrics for a strategy.
    
    Attributes:
        total_trades: Total number of trades
        winning_trades: Number of winning trades
        losing_trades: Number of losing trades
        win_rate: Win rate percentage
        total_profit: Total profit
        total_loss: Total loss
        net_profit: Net profit
        profit_factor: Profit factor (gross profit / gross loss)
        sharpe_ratio: Sharpe ratio
        max_drawdown: Maximum drawdown
        avg_win: Average winning trade
        avg_loss: Average losing trade
        largest_win: Largest winning trade
        largest_loss: Largest losing trade
        total_commission: Total commission paid
        total_slippage: Total slippage
        total_holding_period: Total holding period
        avg_holding_period: Average holding period
        signal_accuracy: Signal accuracy percentage
        last_updated: Last update timestamp
    """
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_profit: float = 0.0
    total_loss: float = 0.0
    net_profit: float = 0.0
    profit_factor: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    largest_win: float = 0.0
    largest_loss: float = 0.0
    total_commission: float = 0.0
    total_slippage: float = 0.0
    total_holding_period: float = 0.0
    avg_holding_period: float = 0.0
    signal_accuracy: float = 0.0
    last_updated: datetime = field(default_factory=datetime.utcnow)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert metrics to dictionary."""
        return {
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "win_rate": self.win_rate,
            "total_profit": self.total_profit,
            "total_loss": self.total_loss,
            "net_profit": self.net_profit,
            "profit_factor": self.profit_factor,
            "sharpe_ratio": self.sharpe_ratio,
            "max_drawdown": self.max_drawdown,
            "avg_win": self.avg_win,
            "avg_loss": self.avg_loss,
            "largest_win": self.largest_win,
            "largest_loss": self.largest_loss,
            "total_commission": self.total_commission,
            "total_slippage": self.total_slippage,
            "avg_holding_period": self.avg_holding_period,
            "signal_accuracy": self.signal_accuracy,
            "last_updated": self.last_updated.isoformat(),
        }


# ============================================================================
# BASE STRATEGY CLASS
# ============================================================================

class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    All strategy implementations must inherit from this class and implement
    the required abstract methods. The base class provides common functionality
    for signal generation, position management, risk management, and performance
    tracking.
    
    Lifecycle:
        1. __init__ -> Configuration and initialization
        2. initialize -> Setup resources and data
        3. on_start -> Start strategy execution
        4. generate_signal -> Generate trading signals (called repeatedly)
        5. on_trade -> Handle completed trades
        6. on_position_update -> Handle position updates
        7. on_stop -> Stop strategy execution
        8. cleanup -> Clean up resources
    
    Usage:
        class MyStrategy(BaseStrategy):
            async def generate_signal(self, market_data):
                # Generate signal logic
                return Signal(...)
            
            async def on_start(self):
                # Setup logic
                pass
            
            async def on_stop(self):
                # Cleanup logic
                pass
    """
    
    def __init__(self, config: StrategyConfig):
        """
        Initialize the strategy.
        
        Args:
            config: Strategy configuration
        """
        self.config = config
        self.state = StrategyState.CREATED
        self.strategy_id = str(uuid.uuid4())
        self.created_at = datetime.utcnow()
        self.start_time: Optional[datetime] = None
        self.stop_time: Optional[datetime] = None
        
        # Positions and orders
        self.positions: Dict[str, Position] = {}
        self.open_orders: Dict[str, Order] = {}
        self.trade_history: List[Trade] = []
        self.signal_history: List[Signal] = []
        
        # Performance metrics
        self.metrics = StrategyMetrics()
        
        # Risk management
        self.equity_curve: List[float] = []
        self.drawdown_curve: List[float] = []
        self.current_drawdown: float = 0.0
        self.peak_equity: float = 0.0
        
        # Backtest support
        self.backtest_mode = config.backtest_mode
        
        # Statistics
        self.stats = {
            "signals_generated": 0,
            "signals_executed": 0,
            "signals_ignored": 0,
            "total_capital_used": 0.0,
            "current_exposure": 0.0,
            "consecutive_wins": 0,
            "consecutive_losses": 0,
            "best_trade": 0.0,
            "worst_trade": 0.0,
        }
        
        # Logger
        self.logger = get_logger(f"{self.__class__.__name__}")
        
        # Callbacks
        self._on_signal_callbacks: List[Callable[[Signal], Awaitable[None]]] = []
        self._on_trade_callbacks: List[Callable[[Trade], Awaitable[None]]] = []
        self._on_position_callbacks: List[Callable[[Position], Awaitable[None]]] = []
        self._on_error_callbacks: List[Callable[[Exception], Awaitable[None]]] = []
        
        # Lock for thread safety
        self._lock = asyncio.Lock()
        
        # Cooldown tracking
        self._last_trade_time: Optional[datetime] = None
        
        self.logger.info(f"Strategy {self.config.name} ({self.strategy_id}) initialized")
    
    # ========================================================================
    # ABSTRACT METHODS
    # ========================================================================
    
    @abstractmethod
    async def generate_signal(
        self,
        market_data: List[MarketData],
    ) -> Optional[Signal]:
        """
        Generate a trading signal based on market data.
        
        This is the core method that each strategy must implement.
        
        Args:
            market_data: List of market data candles
            
        Returns:
            Optional[Signal]: Trading signal or None if no signal
        """
        pass
    
    # ========================================================================
    # VIRTUAL METHODS (Optional Override)
    # ========================================================================
    
    async def initialize(self) -> None:
        """
        Initialize the strategy.
        
        Override this method to perform setup operations.
        """
        self.state = StrategyState.INITIALIZED
        self.logger.info(f"Strategy {self.config.name} initialized")
    
    async def on_start(self) -> None:
        """
        Called when the strategy starts.
        
        Override this method to perform start operations.
        """
        self.state = StrategyState.RUNNING
        self.start_time = datetime.utcnow()
        self.logger.info(f"Strategy {self.config.name} started")
    
    async def on_stop(self) -> None:
        """
        Called when the strategy stops.
        
        Override this method to perform stop operations.
        """
        self.state = StrategyState.STOPPED
        self.stop_time = datetime.utcnow()
        self.logger.info(f"Strategy {self.config.name} stopped")
    
    async def on_trade(self, trade: Trade) -> None:
        """
        Called when a trade is completed.
        
        Override this method to handle trade completions.
        
        Args:
            trade: Completed trade
        """
        await self._update_metrics(trade)
    
    async def on_position_update(self, position: Position) -> None:
        """
        Called when a position is updated.
        
        Override this method to handle position updates.
        
        Args:
            position: Updated position
        """
        pass
    
    async def on_error(self, error: Exception) -> None:
        """
        Called when an error occurs.
        
        Override this method to handle errors.
        
        Args:
            error: Exception that occurred
        """
        self.state = StrategyState.ERROR
        self.logger.error(f"Strategy {self.config.name} error: {error}")
        await self._trigger_error_callbacks(error)
    
    async def cleanup(self) -> None:
        """
        Clean up resources.
        
        Override this method to perform cleanup operations.
        """
        self.state = StrategyState.TERMINATED
        self.logger.info(f"Strategy {self.config.name} cleaned up")
    
    # ========================================================================
    # CALLBACK MANAGEMENT
    # ========================================================================
    
    def on_signal(self, callback: Callable[[Signal], Awaitable[None]]) -> None:
        """
        Register callback for signal generation.
        
        Args:
            callback: Async callback function
        """
        self._on_signal_callbacks.append(callback)
    
    def on_trade(self, callback: Callable[[Trade], Awaitable[None]]) -> None:
        """
        Register callback for trade completions.
        
        Args:
            callback: Async callback function
        """
        self._on_trade_callbacks.append(callback)
    
    def on_position(self, callback: Callable[[Position], Awaitable[None]]) -> None:
        """
        Register callback for position updates.
        
        Args:
            callback: Async callback function
        """
        self._on_position_callbacks.append(callback)
    
    def on_error(self, callback: Callable[[Exception], Awaitable[None]]) -> None:
        """
        Register callback for errors.
        
        Args:
            callback: Async callback function
        """
        self._on_error_callbacks.append(callback)
    
    async def _trigger_signal_callbacks(self, signal: Signal) -> None:
        """Trigger signal callbacks."""
        for callback in self._on_signal_callbacks:
            try:
                await callback(signal)
            except Exception as e:
                self.logger.error(f"Error in signal callback: {e}")
    
    async def _trigger_trade_callbacks(self, trade: Trade) -> None:
        """Trigger trade callbacks."""
        for callback in self._on_trade_callbacks:
            try:
                await callback(trade)
            except Exception as e:
                self.logger.error(f"Error in trade callback: {e}")
    
    async def _trigger_position_callbacks(self, position: Position) -> None:
        """Trigger position callbacks."""
        for callback in self._on_position_callbacks:
            try:
                await callback(position)
            except Exception as e:
                self.logger.error(f"Error in position callback: {e}")
    
    async def _trigger_error_callbacks(self, error: Exception) -> None:
        """Trigger error callbacks."""
        for callback in self._on_error_callbacks:
            try:
                await callback(error)
            except Exception as e:
                self.logger.error(f"Error in error callback: {e}")
    
    # ========================================================================
    # SIGNAL PROCESSING
    # ========================================================================
    
    async def process_signal(
        self,
        signal: Signal,
        market_data: Optional[List[MarketData]] = None,
    ) -> Optional[Order]:
        """
        Process a trading signal and create an order.
        
        Args:
            signal: Trading signal
            market_data: Market data for validation
            
        Returns:
            Optional[Order]: Order to execute or None
        """
        async with self._lock:
            # Check if strategy is running
            if self.state not in [StrategyState.RUNNING, StrategyState.INITIALIZED]:
                self.logger.warning(f"Strategy not running, ignoring signal: {signal.signal_id}")
                self.stats["signals_ignored"] += 1
                return None
            
            # Update statistics
            self.stats["signals_generated"] += 1
            
            # Check confidence threshold
            if signal.confidence < self.config.min_confidence:
                self.logger.debug(
                    f"Signal confidence {signal.confidence:.2f} below threshold {self.config.min_confidence}"
                )
                self.stats["signals_ignored"] += 1
                return None
            
            # Check cooldown
            if self._last_trade_time and self.config.cooldown > 0:
                cooldown_seconds = self.config.cooldown
                elapsed = (datetime.utcnow() - self._last_trade_time).total_seconds()
                if elapsed < cooldown_seconds:
                    self.logger.debug(f"Strategy in cooldown: {elapsed:.1f}s < {cooldown_seconds}s")
                    self.stats["signals_ignored"] += 1
                    return None
            
            # Check position limits
            if len(self.positions) >= self.config.max_positions:
                self.logger.debug(f"Max positions reached: {len(self.positions)}")
                self.stats["signals_ignored"] += 1
                return None
            
            # Handle NEUTRAL and HOLD signals
            if signal.signal_type in [SignalType.NEUTRAL, SignalType.HOLD]:
                self.stats["signals_ignored"] += 1
                return None
            
            # Handle CLOSE signal
            if signal.signal_type == SignalType.CLOSE:
                # Close existing position for symbol
                if signal.symbol in self.positions:
                    position = self.positions[signal.symbol]
                    order = self._create_close_order(position, signal)
                    self.stats["signals_executed"] += 1
                    return order
                return None
            
            # Calculate position size
            position_size = self._calculate_position_size(signal)
            
            # Validate symbol
            if not signal.symbol:
                self.logger.error("Signal missing symbol")
                return None
            
            # Create order
            order = Order(
                symbol=signal.symbol,
                side=OrderSide.BUY if signal.signal_type == SignalType.BUY else OrderSide.SELL,
                order_type=OrderType.LIMIT,
                quantity=position_size,
                price=signal.price,
                stop_loss=signal.stop_loss,
                take_profit=signal.take_profit,
                time_in_force=TimeInForce.GTC,
                client_order_id=f"{self.strategy_id}_{signal.signal_id}",
                metadata={
                    "strategy_id": self.strategy_id,
                    "signal_id": signal.signal_id,
                    "signal_confidence": signal.confidence,
                    "signal_strength": signal.strength.value,
                },
            )
            
            # Store order
            self.open_orders[order.order_id] = order
            self.stats["signals_executed"] += 1
            self.stats["total_capital_used"] += position_size * signal.price
            
            # Trigger callbacks
            await self._trigger_signal_callbacks(signal)
            
            self.logger.info(
                f"Generated order: {order.side.value} {order.quantity:.4f} {order.symbol} "
                f"@ {order.price:.4f} (confidence: {signal.confidence:.2f})"
            )
            
            return order
    
    def _calculate_position_size(self, signal: Signal) -> float:
        """
        Calculate position size based on signal and risk management.
        
        Args:
            signal: Trading signal
            
        Returns:
            float: Position size
        """
        # Use signal's position size if provided
        if signal.position_size:
            return min(signal.position_size, self.config.max_position_size)
        
        # Calculate based on risk
        base_size = self.config.position_size
        
        # Adjust for signal strength
        strength_multiplier = {
            SignalStrength.WEAK: 0.5,
            SignalStrength.MEDIUM: 1.0,
            SignalStrength.STRONG: 1.5,
            SignalStrength.VERY_STRONG: 2.0,
        }.get(signal.strength, 1.0)
        
        # Adjust for confidence
        confidence_multiplier = min(1.5, max(0.5, signal.confidence / 0.5))
        
        # Calculate size
        size = base_size * strength_multiplier * confidence_multiplier
        
        # Apply limits
        size = max(size, self.config.min_position_size)
        size = min(size, self.config.max_position_size)
        
        # Apply risk per trade
        if self.config.risk_per_trade > 0 and signal.price > 0:
            # Use Kelly-like position sizing
            risk_capital = self.metrics.total_profit * self.config.risk_per_trade
            size = min(size, risk_capital / signal.price)
        
        return size
    
    def _create_close_order(self, position: Position, signal: Signal) -> Order:
        """
        Create an order to close a position.
        
        Args:
            position: Position to close
            signal: Closing signal
            
        Returns:
            Order: Close order
        """
        side = OrderSide.SELL if position.side == OrderSide.BUY else OrderSide.BUY
        
        return Order(
            symbol=position.symbol,
            side=side,
            order_type=OrderType.MARKET,
            quantity=position.quantity,
            time_in_force=TimeInForce.IOC,
            client_order_id=f"{self.strategy_id}_close_{position.position_id}",
            metadata={
                "strategy_id": self.strategy_id,
                "position_id": position.position_id,
                "signal_id": signal.signal_id,
                "close_signal": True,
            },
        )
    
    # ========================================================================
    # POSITION MANAGEMENT
    # ========================================================================
    
    async def add_position(self, position: Position) -> None:
        """
        Add a new position.
        
        Args:
            position: Position to add
        """
        async with self._lock:
            self.positions[position.symbol] = position
            self._last_trade_time = datetime.utcnow()
            await self._trigger_position_callbacks(position)
    
    async def update_position(self, position: Position) -> None:
        """
        Update an existing position.
        
        Args:
            position: Updated position
        """
        async with self._lock:
            if position.symbol in self.positions:
                self.positions[position.symbol] = position
                await self._trigger_position_callbacks(position)
    
    async def remove_position(self, symbol: str) -> Optional[Position]:
        """
        Remove a position.
        
        Args:
            symbol: Symbol to remove
            
        Returns:
            Optional[Position]: Removed position or None
        """
        async with self._lock:
            return self.positions.pop(symbol, None)
    
    def get_position(self, symbol: str) -> Optional[Position]:
        """
        Get a position by symbol.
        
        Args:
            symbol: Symbol
            
        Returns:
            Optional[Position]: Position or None
        """
        return self.positions.get(symbol)
    
    def get_positions(self) -> List[Position]:
        """
        Get all positions.
        
        Returns:
            List[Position]: All positions
        """
        return list(self.positions.values())
    
    def get_exposure(self) -> float:
        """
        Get total exposure.
        
        Returns:
            float: Total exposure
        """
        total_exposure = 0.0
        for position in self.positions.values():
            total_exposure += position.quantity * position.entry_price
        return total_exposure
    
    # ========================================================================
    # RISK MANAGEMENT
    # ========================================================================
    
    def check_risk_limits(self) -> bool:
        """
        Check if risk limits are exceeded.
        
        Returns:
            bool: True if risk limits are OK
        """
        # Check max drawdown
        if self.current_drawdown > self.config.max_drawdown:
            self.logger.warning(f"Max drawdown exceeded: {self.current_drawdown:.2%}")
            return False
        
        # Check position limits
        if len(self.positions) >= self.config.max_positions:
            self.logger.warning(f"Max positions reached: {len(self.positions)}")
            return False
        
        # Check exposure
        exposure = self.get_exposure()
        if exposure > self.config.max_position_size * 2:
            self.logger.warning(f"Exposure too high: {exposure:.2f}")
            return False
        
        return True
    
    def update_drawdown(self, equity: float) -> None:
        """
        Update drawdown based on current equity.
        
        Args:
            equity: Current equity
        """
        if equity > self.peak_equity:
            self.peak_equity = equity
        
        if self.peak_equity > 0:
            self.current_drawdown = (self.peak_equity - equity) / self.peak_equity
            self.drawdown_curve.append(self.current_drawdown)
        
        self.equity_curve.append(equity)
    
    def get_risk_metrics(self) -> Dict[str, float]:
        """
        Get risk metrics.
        
        Returns:
            Dict[str, float]: Risk metrics
        """
        return {
            "current_drawdown": self.current_drawdown,
            "max_drawdown": self.metrics.max_drawdown,
            "exposure": self.get_exposure(),
            "position_count": len(self.positions),
            "peak_equity": self.peak_equity,
            "current_equity": self.equity_curve[-1] if self.equity_curve else 0,
        }
    
    # ========================================================================
    # PERFORMANCE METRICS
    # ========================================================================
    
    async def _update_metrics(self, trade: Trade) -> None:
        """
        Update performance metrics with a completed trade.
        
        Args:
            trade: Completed trade
        """
        self.metrics.total_trades += 1
        self.metrics.total_commission += trade.commission
        self.metrics.total_slippage += trade.slippage
        
        # Calculate trade P&L
        pnl = trade.pnl or 0.0
        
        if pnl > 0:
            self.metrics.winning_trades += 1
            self.metrics.total_profit += pnl
            self.stats["consecutive_wins"] += 1
            self.stats["consecutive_losses"] = 0
            if pnl > self.stats["best_trade"]:
                self.stats["best_trade"] = pnl
            if pnl > self.metrics.largest_win:
                self.metrics.largest_win = pnl
        else:
            self.metrics.losing_trades += 1
            self.metrics.total_loss += abs(pnl)
            self.stats["consecutive_wins"] = 0
            self.stats["consecutive_losses"] += 1
            if pnl < self.stats["worst_trade"]:
                self.stats["worst_trade"] = pnl
            if abs(pnl) > self.metrics.largest_loss:
                self.metrics.largest_loss = abs(pnl)
        
        # Update derived metrics
        total_trades = self.metrics.total_trades
        if total_trades > 0:
            self.metrics.win_rate = (self.metrics.winning_trades / total_trades) * 100
            self.metrics.net_profit = self.metrics.total_profit - self.metrics.total_loss
            
            if self.metrics.total_loss > 0:
                self.metrics.profit_factor = self.metrics.total_profit / self.metrics.total_loss
            else:
                self.metrics.profit_factor = self.metrics.total_profit if self.metrics.total_profit > 0 else 1.0
            
            if self.metrics.winning_trades > 0:
                self.metrics.avg_win = self.metrics.total_profit / self.metrics.winning_trades
            
            if self.metrics.losing_trades > 0:
                self.metrics.avg_loss = self.metrics.total_loss / self.metrics.losing_trades
            
            # Update max drawdown
            if self.metrics.max_drawdown < self.current_drawdown:
                self.metrics.max_drawdown = self.current_drawdown
            
            # Update holding period
            if trade.entry_time and trade.exit_time:
                holding_period = (trade.exit_time - trade.entry_time).total_seconds() / 3600  # hours
                self.metrics.total_holding_period += holding_period
                self.metrics.avg_holding_period = self.metrics.total_holding_period / total_trades
        
        self.metrics.last_updated = datetime.utcnow()
        
        # Log performance
        self.logger.info(
            f"Trade completed: {trade.symbol} {trade.side.value} "
            f"P&L: ${pnl:.2f} | Win rate: {self.metrics.win_rate:.1f}% | "
            f"Total P&L: ${self.metrics.net_profit:.2f}"
        )
    
    def get_metrics(self) -> StrategyMetrics:
        """
        Get strategy metrics.
        
        Returns:
            StrategyMetrics: Strategy metrics
        """
        return self.metrics
    
    def get_stats(self) -> Dict[str, Any]:
        """
        Get strategy statistics.
        
        Returns:
            Dict[str, Any]: Strategy statistics
        """
        return {
            **self.stats,
            "state": self.state.value,
            "uptime": (datetime.utcnow() - self.start_time).total_seconds() if self.start_time else 0,
            "positions": len(self.positions),
            "open_orders": len(self.open_orders),
            "total_trades": self.metrics.total_trades,
        }
    
    # ========================================================================
    # BACKTESTING SUPPORT
    # ========================================================================
    
    def enable_backtest(self) -> None:
        """
        Enable backtest mode.
        """
        self.backtest_mode = True
        self.logger.info("Backtest mode enabled")
    
    def disable_backtest(self) -> None:
        """
        Disable backtest mode.
        """
        self.backtest_mode = False
        self.logger.info("Backtest mode disabled")
    
    async def backtest_step(
        self,
        market_data: List[MarketData],
    ) -> Optional[Signal]:
        """
        Run one backtest step.
        
        Args:
            market_data: Market data for this step
            
        Returns:
            Optional[Signal]: Generated signal
        """
        if not self.backtest_mode:
            self.logger.warning("Backtest step called but backtest mode is disabled")
            return None
        
        return await self.generate_signal(market_data)
    
    # ========================================================================
    # UTILITY METHODS
    # ========================================================================
    
    def calculate_sharpe_ratio(
        self,
        returns: List[float],
        risk_free_rate: float = 0.02,
    ) -> float:
        """
        Calculate Sharpe ratio from returns.
        
        Args:
            returns: List of returns
            risk_free_rate: Risk-free rate (annualized)
            
        Returns:
            float: Sharpe ratio
        """
        if not returns:
            return 0.0
        
        avg_return = sum(returns) / len(returns)
        std_return = (sum((r - avg_return) ** 2 for r in returns) / len(returns)) ** 0.5
        
        if std_return == 0:
            return 0.0
        
        # Annualize (assuming daily returns)
        annualized_return = avg_return * 252
        annualized_std = std_return * (252 ** 0.5)
        
        return (annualized_return - risk_free_rate) / annualized_std
    
    def calculate_kelly_criterion(
        self,
        win_rate: float,
        avg_win: float,
        avg_loss: float,
    ) -> float:
        """
        Calculate Kelly criterion for position sizing.
        
        Args:
            win_rate: Win rate (0-1)
            avg_win: Average win
            avg_loss: Average loss
            
        Returns:
            float: Kelly fraction
        """
        if avg_loss == 0:
            return 0.0
        
        win_loss_ratio = avg_win / avg_loss
        kelly = win_rate - (1 - win_rate) / win_loss_ratio
        
        # Cap at 25% for safety
        return max(0, min(0.25, kelly))
    
    def get_strategy_info(self) -> Dict[str, Any]:
        """
        Get strategy information.
        
        Returns:
            Dict[str, Any]: Strategy information
        """
        return {
            "strategy_id": self.strategy_id,
            "name": self.config.name,
            "type": self.config.strategy_type.value,
            "state": self.state.value,
            "symbol": self.config.symbol,
            "timeframe": self.config.timeframe,
            "created_at": self.created_at.isoformat(),
            "start_time": self.start_time.isoformat() if self.start_time else None,
            "stop_time": self.stop_time.isoformat() if self.stop_time else None,
            "backtest_mode": self.backtest_mode,
            "metrics": self.metrics.to_dict(),
            "stats": self.get_stats(),
            "risk_metrics": self.get_risk_metrics(),
        }
    
    # ========================================================================
    # CONTEXT MANAGER
    # ========================================================================
    
    async def __aenter__(self):
        """Async context manager entry."""
        await self.initialize()
        await self.on_start()
        return self
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit."""
        await self.on_stop()
        await self.cleanup()
    
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}({self.config.name}, {self.state.value})>"


# ============================================================================
# EXPORTS
# ============================================================================

__all__ = [
    # Enums
    "StrategyType",
    "StrategyState",
    "SignalType",
    "SignalStrength",
    
    # Models
    "Signal",
    "StrategyConfig",
    "StrategyMetrics",
    
    # Base class
    "BaseStrategy",
]
