"""
Swing Bot Utilities Package
============================

This package provides utility modules for the Swing Bot trading system.
Includes various helper functions and utilities organized by functionality.
"""

# Core utilities
from .helpers import (
    Helpers,
    ensure_dir,
    ensure_file,
    load_json,
    save_json,
    load_yaml,
    save_yaml,
    load_pickle,
    save_pickle,
    get_file_hash,
    get_text_hash,
    get_data_hash,
    get_file_size,
    get_file_age,
    is_file_older_than,
    find_files,
    find_files_by_extension,
    get_available_port,
    get_current_time,
    get_current_timestamp,
    format_datetime,
    parse_datetime,
    get_environment,
    is_production,
    is_development,
    is_debug,
    get_hostname,
    get_pid,
    get_cpu_count,
    get_memory_usage,
    get_cpu_usage,
    get_disk_usage,
    get_network_usage,
    format_bytes,
    format_duration,
    format_percentage,
    safe_divide,
    safe_int,
    safe_float,
    safe_string,
    safe_dict,
    safe_list,
    truncate_string,
    get_class_name,
    get_function_name,
    get_module_name,
    get_full_name,
    import_module,
    import_class,
    get_signature,
    get_parameters,
    get_parameter_names,
    is_async_function,
    is_class_method,
    is_static_method,
    is_property,
    is_lambda,
    is_generator,
    get_default_args,
    get_annotations,
    get_docstring,
    get_source_code,
    get_lineno,
    get_file_path,
    get_stack,
    get_caller_frame,
    get_caller_function,
    get_caller_file,
    get_caller_line,
)

from .decorators import (
    timer,
    async_timer,
    retry,
    async_retry,
    timeout,
    async_timeout,
    singleton,
    synchronized,
    async_synchronized,
    log_execution,
    async_log_execution,
    cache,
    async_cache,
    validate_args,
    async_validate_args,
    rate_limit,
    async_rate_limit,
    deprecated,
    async_deprecated,
    requires,
    async_requires,
    class_property,
    static_class_property,
    singleton_method,
    async_singleton_method,
    enforce_type,
    async_enforce_type,
)

from .validators import (
    ValidationError,
    Validator,
    DataValidator,
    OrderValidator,
    RiskValidator,
    ConfigValidator,
    MarketDataValidator,
    TimeValidator,
    SymbolValidator,
    PositionValidator,
    PortfolioValidator,
    TradeValidator,
    validate_data,
    is_valid_data,
    get_validation_errors,
)

from .math_utils import (
    MathUtils,
    round_to,
    clamp,
    lerp,
    normalize,
    zscore,
    percentile,
    moving_average,
    exponential_moving_average,
    standard_deviation,
    variance,
    correlation,
    covariance,
    linear_regression,
    r_squared,
    p_value,
    log_return,
    simple_return,
    sharpe_ratio,
    sortino_ratio,
    max_drawdown,
    volatility,
    beta,
    alpha,
    kelly_criterion,
    half_life,
    hurst_exponent,
    correlation_matrix,
    covariance_matrix,
    risk_parity_weights,
)

from .converters import (
    Converters,
    to_int,
    to_float,
    to_decimal,
    to_bool,
    to_str,
    to_bytes,
    to_json,
    to_list,
    to_datetime,
    to_date,
    to_timestamp,
    to_base64,
    from_base64,
    to_hex,
    from_hex,
    to_binary,
    from_binary,
    to_percent,
    from_percent,
    to_currency,
    from_currency,
    to_time,
    to_timedelta,
    to_iso_format,
    from_iso_format,
    to_dataframe,
    to_dict,
    to_numpy,
    to_series,
)

from .formatters import (
    Formatters,
    format_price,
    format_quantity,
    format_percentage,
    format_currency,
    format_volume,
    format_duration,
    format_datetime,
    format_date,
    format_time,
    format_timestamp,
    format_interval,
    format_size,
    format_number,
    format_hex,
    format_json,
    format_yaml,
    format_csv,
    format_table,
    format_pandas,
    format_numpy,
    format_dict,
    format_list,
    format_error,
    format_status,
    format_progress,
    format_address,
)

from .string_utils import (
    StringUtils,
    to_snake_case,
    to_camel_case,
    to_pascal_case,
    to_kebab_case,
    to_title_case,
    to_constant_case,
    to_sentence_case,
    truncate,
    strip_accents,
    slugify,
    is_valid_email,
    is_valid_url,
    is_valid_phone,
    is_valid_symbol,
    is_valid_hex,
    is_valid_base64,
    is_valid_json,
    is_valid_uuid,
    extract_numbers,
    extract_words,
    extract_emails,
    extract_urls,
    strip_html,
    escape_html,
    unescape_html,
    hash_string,
    encode_base64,
    decode_base64,
    format_bytes as format_bytes_str,
    format_duration as format_duration_str,
    format_currency as format_currency_str,
    format_percentage as format_percentage_str,
    pluralize,
    is_blank,
    default_if_blank,
)

from .date_utils import (
    DateUtils,
    DATE_FORMATS,
    now,
    now_local,
    today,
    utcnow,
    to_utc,
    to_local,
    to_timezone,
    parse_date,
    format_date,
    format_timestamp,
    parse_timestamp,
    add_days,
    add_weeks,
    add_months,
    add_years,
    diff_days,
    diff_seconds,
    diff_minutes,
    diff_hours,
    get_weekday,
    get_weekday_name,
    get_month_name,
    get_days_in_month,
    get_week_number,
    get_quarter,
    get_quarter_start,
    get_quarter_end,
    get_year_start,
    get_year_end,
    get_month_start,
    get_month_end,
    get_week_start,
    get_week_end,
    is_weekday,
    is_weekend,
    is_market_open,
    get_timezone_offset,
    get_timezone_name,
    generate_date_range,
    generate_trading_days,
    get_trading_days_count,
)

from .file_utils import (
    FileUtils,
    ensure_dir as file_ensure_dir,
    ensure_file as file_ensure_file,
    read_text,
    write_text,
    read_bytes,
    write_bytes,
    read_lines,
    write_lines,
    read_json as file_read_json,
    write_json as file_write_json,
    read_yaml as file_read_yaml,
    write_yaml as file_write_yaml,
    read_pickle as file_read_pickle,
    write_pickle as file_write_pickle,
    read_csv as file_read_csv,
    write_csv as file_write_csv,
    get_file_size as file_get_file_size,
    get_file_modified_time,
    get_file_created_time,
    get_file_hash as file_get_file_hash,
    get_file_extension,
    get_file_name,
    get_file_name_without_extension,
    get_file_dir,
    copy_file,
    move_file,
    delete_file,
    delete_dir,
    list_files,
    list_files_by_extension,
    find_files as file_find_files,
    get_temp_dir,
    get_temp_file,
    create_temp_file,
    create_temp_dir,
    is_file,
    is_dir,
    is_symlink,
    exists,
    get_absolute_path,
    get_relative_path,
    normalize_path,
    join_paths,
    split_path,
    change_extension,
    get_mime_type,
    is_text_file,
    get_line_count,
    get_word_count,
    get_char_count,
    compress_file,
    decompress_file,
    compress_dir,
    decompress_dir,
)

from .crypto_utils import (
    CryptoUtils,
    generate_key,
    generate_salt,
    hash_password,
    verify_password,
    hash_data,
    hash_file,
    hmac_sign,
    hmac_verify,
    generate_fernet_key,
    encrypt_fernet,
    decrypt_fernet,
    generate_rsa_key_pair,
    encrypt_rsa,
    decrypt_rsa,
    sign_data,
    verify_signature,
    derive_key,
    generate_jwt_token,
    decode_jwt_token,
    verify_jwt_token,
    generate_api_key,
    generate_otp_secret,
    generate_totp,
    verify_totp,
    generate_hotp,
    verify_hotp,
    secure_compare,
)

from .network_utils import (
    NetworkProtocol,
    RequestMethod,
    NetworkStats,
    NetworkClient,
    AsyncNetworkClient,
    WebSocketManager,
    is_valid_ip,
    is_valid_port,
    is_valid_url as network_is_valid_url,
    resolve_dns,
    ping_host,
    get_local_ip,
    get_public_ip,
    check_port,
    get_service_status,
)

from .backoff import (
    BackoffType,
    BackoffConfig,
    BackoffCalculator,
    RetryState,
    RetryContext,
    retry as backoff_retry,
    async_retry as backoff_async_retry,
    NO_BACKOFF,
    FIXED_BACKOFF,
    LINEAR_BACKOFF,
    EXPONENTIAL_BACKOFF,
    EXPONENTIAL_JITTER_BACKOFF,
    FULL_JITTER_BACKOFF,
    DECORRELATED_JITTER_BACKOFF,
)

from .cache import (
    CacheEntry,
    CacheStats,
    BaseCache,
    MemoryCache,
    DiskCache,
    DistributedCache,
    cached,
    async_cached,
)

from .locks import (
    LockState,
    LockType,
    LockStats,
    ThreadLock,
    ReadWriteLock,
    Semaphore,
    DistributedLock,
    LockManager,
    acquire_lock,
    acquire_read_lock,
    acquire_write_lock,
    synchronized as lock_synchronized,
    lock_manager,
)

from .threads import (
    ThreadState,
    ThreadInfo,
    ThreadSafeQueue,
    ThreadPool,
    AsyncThreadPool,
    ThreadSafeCounter,
    ThreadSafeDict,
    synchronized as thread_synchronized,
    run_in_thread,
    run_with_timeout,
)

from .timers import (
    TimerState,
    TimerType,
    TimerStats,
    Timer,
    TimerManager,
    timer_manager,
    create_interval_timer,
    create_delayed_timer,
    create_countdown_timer,
    time_function,
    async_time_function,
    sleep_until,
    async_sleep_until,
    get_timestamp,
    measure_time,
)

from .queues import (
    QueueType,
    QueueState,
    QueueStats,
    QueueItem,
    BaseQueue,
    FIFOQueue,
    LIFOQueue,
    PriorityQueue,
    DelayedQueue,
    QueueManager,
    AsyncQueue,
    create_queue,
    create_async_queue,
    queue_manager,
)

from .pools import (
    PoolState,
    PoolStats,
    PooledObject,
    ObjectPool,
    ConnectionPool,
    ThreadPool as PoolThreadPool,
    create_object_pool,
    create_connection_pool,
    create_thread_pool,
    register_pool,
    get_pool,
    close_all_pools,
    _pool_registry,
    _pool_registry_lock,
)

from .retry import (
    RetryConfig,
    RetryError,
    calculate_backoff as retry_calculate_backoff,
    should_retry_exception,
    retry as retry_decorator,
    async_retry as async_retry_decorator,
    RetryContext as RetryContextClass,
    retry_call,
    retry_call_async,
    DEFAULT_RETRY_CONFIG,
    FAST_RETRY_CONFIG,
    AGGRESSIVE_RETRY_CONFIG,
    VERY_AGGRESSIVE_RETRY_CONFIG,
    NO_RETRY_CONFIG,
)

from .async_utils import (
    AsyncUtils,
    AsyncTaskManager,
    AsyncRateLimiter,
    async_wrap,
    async_retry as async_retry_util,
)

__all__ = [
    # Helpers
    'Helpers', 'ensure_dir', 'ensure_file', 'load_json', 'save_json',
    'load_yaml', 'save_yaml', 'load_pickle', 'save_pickle',
    'get_file_hash', 'get_text_hash', 'get_data_hash',
    'get_file_size', 'get_file_age', 'is_file_older_than',
    'find_files', 'find_files_by_extension', 'get_available_port',
    'get_current_time', 'get_current_timestamp', 'format_datetime',
    'parse_datetime', 'get_environment', 'is_production',
    'is_development', 'is_debug', 'get_hostname', 'get_pid',
    'get_cpu_count', 'get_memory_usage', 'get_cpu_usage',
    'get_disk_usage', 'get_network_usage', 'format_bytes',
    'format_duration', 'format_percentage', 'safe_divide',
    'safe_int', 'safe_float', 'safe_string', 'safe_dict',
    'safe_list', 'truncate_string', 'get_class_name',
    'get_function_name', 'get_module_name', 'get_full_name',
    'import_module', 'import_class', 'get_signature',
    'get_parameters', 'get_parameter_names', 'is_async_function',
    'is_class_method', 'is_static_method', 'is_property',
    'is_lambda', 'is_generator', 'get_default_args',
    'get_annotations', 'get_docstring', 'get_source_code',
    'get_lineno', 'get_file_path', 'get_stack', 'get_caller_frame',
    'get_caller_function', 'get_caller_file', 'get_caller_line',
    
    # Validators
    'ValidationError', 'Validator', 'DataValidator', 'OrderValidator',
    'RiskValidator', 'ConfigValidator', 'MarketDataValidator',
    'TimeValidator', 'SymbolValidator', 'PositionValidator',
    'PortfolioValidator', 'TradeValidator', 'validate_data',
    'is_valid_data', 'get_validation_errors',
    
    # Decorators
    'timer', 'async_timer', 'retry', 'async_retry',
    'timeout', 'async_timeout', 'singleton', 'synchronized',
    'async_synchronized', 'log_execution', 'async_log_execution',
    'cache', 'async_cache', 'validate_args', 'async_validate_args',
    'rate_limit', 'async_rate_limit', 'deprecated', 'async_deprecated',
    'requires', 'async_requires', 'class_property',
    'static_class_property', 'singleton_method', 'async_singleton_method',
    'enforce_type', 'async_enforce_type',
    
    # Math Utils
    'MathUtils', 'round_to', 'clamp', 'lerp', 'normalize', 'zscore',
    'percentile', 'moving_average', 'exponential_moving_average',
    'standard_deviation', 'variance', 'correlation', 'covariance',
    'linear_regression', 'r_squared', 'p_value', 'log_return',
    'simple_return', 'sharpe_ratio', 'sortino_ratio', 'max_drawdown',
    'volatility', 'beta', 'alpha', 'kelly_criterion', 'half_life',
    'hurst_exponent', 'correlation_matrix', 'covariance_matrix',
    'risk_parity_weights',
    
    # Converters
    'Converters', 'to_int', 'to_float', 'to_decimal', 'to_bool',
    'to_str', 'to_bytes', 'to_json', 'to_list', 'to_datetime',
    'to_date', 'to_timestamp', 'to_base64', 'from_base64', 'to_hex',
    'from_hex', 'to_binary', 'from_binary', 'to_percent',
    'from_percent', 'to_currency', 'from_currency', 'to_time',
    'to_timedelta', 'to_iso_format', 'from_iso_format',
    'to_dataframe', 'to_dict', 'to_numpy', 'to_series',
    
    # Formatters
    'Formatters', 'format_price', 'format_quantity', 'format_percentage',
    'format_currency', 'format_volume', 'format_duration',
    'format_datetime', 'format_date', 'format_time', 'format_timestamp',
    'format_interval', 'format_size', 'format_number', 'format_hex',
    'format_json', 'format_yaml', 'format_csv', 'format_table',
    'format_pandas', 'format_numpy', 'format_dict', 'format_list',
    'format_error', 'format_status', 'format_progress', 'format_address',
    
    # String Utils
    'StringUtils', 'to_snake_case', 'to_camel_case', 'to_pascal_case',
    'to_kebab_case', 'to_title_case', 'to_constant_case',
    'to_sentence_case', 'truncate', 'strip_accents', 'slugify',
    'is_valid_email', 'is_valid_url', 'is_valid_phone', 'is_valid_symbol',
    'is_valid_hex', 'is_valid_base64', 'is_valid_json', 'is_valid_uuid',
    'extract_numbers', 'extract_words', 'extract_emails', 'extract_urls',
    'strip_html', 'escape_html', 'unescape_html', 'hash_string',
    'encode_base64', 'decode_base64', 'format_bytes_str',
    'format_duration_str', 'format_currency_str',
    'format_percentage_str', 'pluralize', 'is_blank', 'default_if_blank',
    
    # Date Utils
    'DateUtils', 'DATE_FORMATS', 'now', 'now_local', 'today', 'utcnow',
    'to_utc', 'to_local', 'to_timezone', 'parse_date', 'format_date',
    'format_timestamp', 'parse_timestamp', 'add_days', 'add_weeks',
    'add_months', 'add_years', 'diff_days', 'diff_seconds',
    'diff_minutes', 'diff_hours', 'get_weekday', 'get_weekday_name',
    'get_month_name', 'get_days_in_month', 'get_week_number',
    'get_quarter', 'get_quarter_start', 'get_quarter_end',
    'get_year_start', 'get_year_end', 'get_month_start', 'get_month_end',
    'get_week_start', 'get_week_end', 'is_weekday', 'is_weekend',
    'is_market_open', 'get_timezone_offset', 'get_timezone_name',
    'generate_date_range', 'generate_trading_days',
    'get_trading_days_count',
    
    # File Utils
    'FileUtils', 'file_ensure_dir', 'file_ensure_file', 'read_text',
    'write_text', 'read_bytes', 'write_bytes', 'read_lines',
    'write_lines', 'file_read_json', 'file_write_json', 'file_read_yaml',
    'file_write_yaml', 'file_read_pickle', 'file_write_pickle',
    'file_read_csv', 'file_write_csv', 'file_get_file_size',
    'get_file_modified_time', 'get_file_created_time',
    'file_get_file_hash', 'get_file_extension', 'get_file_name',
    'get_file_name_without_extension', 'get_file_dir', 'copy_file',
    'move_file', 'delete_file', 'delete_dir', 'list_files',
    'list_files_by_extension', 'file_find_files', 'get_temp_dir',
    'get_temp_file', 'create_temp_file', 'create_temp_dir', 'is_file',
    'is_dir', 'is_symlink', 'exists', 'get_absolute_path',
    'get_relative_path', 'normalize_path', 'join_paths', 'split_path',
    'change_extension', 'get_mime_type', 'is_text_file',
    'get_line_count', 'get_word_count', 'get_char_count',
    'compress_file', 'decompress_file', 'compress_dir', 'decompress_dir',
    
    # Crypto Utils
    'CryptoUtils', 'generate_key', 'generate_salt', 'hash_password',
    'verify_password', 'hash_data', 'hash_file', 'hmac_sign',
    'hmac_verify', 'generate_fernet_key', 'encrypt_fernet',
    'decrypt_fernet', 'generate_rsa_key_pair', 'encrypt_rsa',
    'decrypt_rsa', 'sign_data', 'verify_signature', 'derive_key',
    'generate_jwt_token', 'decode_jwt_token', 'verify_jwt_token',
    'generate_api_key', 'generate_otp_secret', 'generate_totp',
    'verify_totp', 'generate_hotp', 'verify_hotp', 'secure_compare',
    
    # Network Utils
    'NetworkProtocol', 'RequestMethod', 'NetworkStats', 'NetworkClient',
    'AsyncNetworkClient', 'WebSocketManager', 'is_valid_ip',
    'is_valid_port', 'network_is_valid_url', 'resolve_dns', 'ping_host',
    'get_local_ip', 'get_public_ip', 'check_port', 'get_service_status',
    
    # Backoff Utils
    'BackoffType', 'BackoffConfig', 'BackoffCalculator', 'RetryState',
    'RetryContext', 'backoff_retry', 'backoff_async_retry', 'NO_BACKOFF',
    'FIXED_BACKOFF', 'LINEAR_BACKOFF', 'EXPONENTIAL_BACKOFF',
    'EXPONENTIAL_JITTER_BACKOFF', 'FULL_JITTER_BACKOFF',
    'DECORRELATED_JITTER_BACKOFF',
    
    # Cache
    'CacheEntry', 'CacheStats', 'BaseCache', 'MemoryCache', 'DiskCache',
    'DistributedCache', 'cached', 'async_cached',
    
    # Locks
    'LockState', 'LockType', 'LockStats', 'ThreadLock', 'ReadWriteLock',
    'Semaphore', 'DistributedLock', 'LockManager', 'acquire_lock',
    'acquire_read_lock', 'acquire_write_lock', 'lock_synchronized',
    'lock_manager',
    
    # Threads
    'ThreadState', 'ThreadInfo', 'ThreadSafeQueue', 'ThreadPool',
    'AsyncThreadPool', 'ThreadSafeCounter', 'ThreadSafeDict',
    'thread_synchronized', 'run_in_thread', 'run_with_timeout',
    
    # Timers
    'TimerState', 'TimerType', 'TimerStats', 'Timer', 'TimerManager',
    'timer_manager', 'create_interval_timer', 'create_delayed_timer',
    'create_countdown_timer', 'time_function', 'async_time_function',
    'sleep_until', 'async_sleep_until', 'get_timestamp', 'measure_time',
    
    # Queues
    'QueueType', 'QueueState', 'QueueStats', 'QueueItem', 'BaseQueue',
    'FIFOQueue', 'LIFOQueue', 'PriorityQueue', 'DelayedQueue',
    'QueueManager', 'AsyncQueue', 'create_queue', 'create_async_queue',
    'queue_manager',
    
    # Pools
    'PoolState', 'PoolStats', 'PooledObject', 'ObjectPool',
    'ConnectionPool', 'PoolThreadPool', 'create_object_pool',
    'create_connection_pool', 'create_thread_pool', 'register_pool',
    'get_pool', 'close_all_pools', '_pool_registry', '_pool_registry_lock',
    
    # Retry
    'RetryConfig', 'RetryError', 'retry_calculate_backoff',
    'should_retry_exception', 'retry_decorator', 'async_retry_decorator',
    'RetryContextClass', 'retry_call', 'retry_call_async',
    'DEFAULT_RETRY_CONFIG', 'FAST_RETRY_CONFIG', 'AGGRESSIVE_RETRY_CONFIG',
    'VERY_AGGRESSIVE_RETRY_CONFIG', 'NO_RETRY_CONFIG',
    
    # Async Utils
    'AsyncUtils', 'AsyncTaskManager', 'AsyncRateLimiter', 'async_wrap',
    'async_retry_util',
]

# Version information
__version__ = "3.0.0"
__author__ = "NEXUS QUANTUM LTD"
__copyright__ = "© 2026 NEXUS QUANTUM LTD - All Rights Reserved"
